/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.23
 * Generated at: 2023-04-08 07:16:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Login</title>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("*{\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("body{\r\n");
      out.write("    width: 100vw;\r\n");
      out.write("    height: 100vh;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    flex-direction: column;\r\n");
      out.write("    background-color: #8EC5FC;\r\n");
      out.write("    background-image: linear-gradient(62deg, #8EC5FC 0%, #E0C3FC 100%);\r\n");
      out.write("    font-family: Arial, Helvetica, sans-serif;\r\n");
      out.write("}\r\n");
      out.write(".login\r\n");
      out.write("{\r\n");
      out.write("    width: 400px;\r\n");
      out.write("    height: 350px;\r\n");
      out.write("    padding: 20px;\r\n");
      out.write("    box-shadow: rgba(0, 0, 0, 0.35) 0px 5px 15px;\r\n");
      out.write("    margin-top: 10px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".login form\r\n");
      out.write("{\r\n");
      out.write("    position: relative;\r\n");
      out.write("}\r\n");
      out.write(".login .input label\r\n");
      out.write("{\r\n");
      out.write("    font-size: 20px;\r\n");
      out.write("}\r\n");
      out.write(".login .input input\r\n");
      out.write("{\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 30px;\r\n");
      out.write("    margin-top: 10px;\r\n");
      out.write("    border: none;\r\n");
      out.write("    outline: none;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    padding-inline: 5px;\r\n");
      out.write("    margin-bottom: 5px;\r\n");
      out.write("}\r\n");
      out.write(".login #sub\r\n");
      out.write("{\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    margin-top: 20px;\r\n");
      out.write("    height: 40px;\r\n");
      out.write("    text-transform: uppercase;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    letter-spacing: 1px;\r\n");
      out.write("    border: none;\r\n");
      out.write("    outline: none;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    box-shadow: rgba(0, 0, 0, 0.24) 0px 3px 8px;\r\n");
      out.write("    background-image: linear-gradient( 135deg, #69FF97 10%, #00E4FF 100%);\r\n");
      out.write("}\r\n");
      out.write(".login a\r\n");
      out.write("{\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    margin-top: 20px;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    color: black;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    font-size: 20px;\r\n");
      out.write("}\r\n");
      out.write(".login a span\r\n");
      out.write("{\r\n");
      out.write("    text-decoration: underline;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write(" <h1>Login To Start Shopping</h1>\r\n");
      out.write("    <div class=\"login\">\r\n");
      out.write("        <form action=\"log\" method=\"post\">\r\n");
      out.write("            <div class=\"input\">\r\n");
      out.write("                <label for=\"username\">Username</label><span style=\"color: red;\">*</span><br>\r\n");
      out.write("                <input type=\"text\" name=\"username\" id=\"textBox\" placeholder=\"username\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"input\">\r\n");
      out.write("                <label for=\"password\">Password</label><span style=\"color: red;\">*</span><br>\r\n");
      out.write("                <input type=\"text\" name=\"password\" id=\"textBox\" placeholder=\"password\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("            <input type=\"submit\" id=\"sub\" value=\"login\"><br>\r\n");
      out.write("            <a href=\"register.jsp\">New User? <span>Register here</span></a>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
